spring:
  datasource:
    url: jdbc:postgresql://localhost/testdb
    username: testuser
    password: junipass
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost/testdb
  jpa:  
    database: default
    generate-ddl: true
    show-sql: false
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # disable an ugly exception at start 
    
    
server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: ouvresToi
    keyStoreType: PKCS12
    keyAlias: juniter
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/svg+xml



juniter:
  network:
    remote: https://[fe80::f816:3eff:fed4:3e0b]/
  simpleloader:
    enabled: true  
  graphviz:
    enabled: true
  graphql:
    enabled: true
  bma:
    enabled: true
  ws2p:
    enabled: true
  utils:
    enabled: false
    
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

#spring.jpa.show-sql: true
#spring.session.store-type: none

#spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration   

#spring.mvc.view.prefix: /WEB-INF/view/
#spring.mvc.view.suffix: .jsp


