##
## =========================== Spring Specific Confs ===========================
##
spring:
  output.ansi.enabled: DETECT # Colored logs : DETECT|ALWAYS|NEVER 
  session.store-type: none # jdbc|mongo|none|redis|hazelcast

  datasource:
    url: jdbc:postgresql://localhost/testdb
    username: testuser
    password: junipass
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost/testdb

  jpa:  
    database: default 
    generate-ddl: true
    show-sql: false
    hibernate.ddl-auto: create-drop
    properties.hibernate.jdbc:
          lob.non_contextual_creation: true # disable an ugly exception at start 
#  mvc.view:
#      prefix: /WEB-INF/view/
#      suffix: .jsp
#  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration 
      


##
## =========================== Web Server Configs ===========================
## 

server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: ouvresToi
    keyStoreType: PKCS12
    keyAlias: juniter
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/svg+xml

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true


##
## =========================== Juniter Configs ===========================
## 
juniter:
  network:
    trusted: https://g1.bertrandbenjamin.com/,https://g1.duniter.org/,https://duniter.g1.1000i100.fr/,https://duniter.nayya.org/
    bulkSize: 500
  simpleloader:
    enabled: true  
  graphviz:
    enabled: true
  graphql:
    enabled: true
  bma:
    enabled: true
  ws2p:
    enabled: true
  utils:
    enabled: false
    

##
## =========================== Logging Configs ===========================
##    
logging:
  path: /var/log/juniter
#  file: juniter.log
  level:
    root: warn
    org.springframework.web: warn
    org.hibernate.SQL: warn
    juniter: info
#hibernate.show_sql: false
    
    
    

