--DROP DATABASE testdb;
--
--CREATE DATABASE testdb
--  WITH OWNER = testuser
--       ENCODING = 'UTF8'
--       TABLESPACE = pg_default
--       LC_COLLATE = 'en_US.UTF-8'
--       LC_CTYPE = 'en_US.UTF-8'
--       CONNECTION LIMIT = -1;
--
--
--
--
