name: Tests CI

on:
  push:
    branches:
      - master
      - release/*

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test junigeek
        run: |
          ./gradlew :junigeek:test
          ./gradlew :junigeek:testsJar
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: junigeek-tests
          path: junigeek/build/libs/junigeek-1.0.0-SNAPSHOT-tests.jar

      - name: Test juniterriens
        run: |
          ./gradlew :juniterriens:test
          ./gradlew :juniterriens:testsJar
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: juniterriens-tests
          path: juniterriens/build/libs/juniterriens-1.0.0-SNAPSHOT-tests.jar

      - name: Test core
        run: |
          ./gradlew :core:test
          ./gradlew :core:testsJar
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: core-tests
          path: core/build/libs/core-1.0.0-SNAPSHOT-tests.jar

  sourcesAndDoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Sources core
        run: ./gradlew :core:sourcesJar

      - name: Javadoc core
        run: ./gradlew :core:javadocJar

      - name: Maven Deploy
        run: mvn deploy -Dregistry=https://maven.pkg.github.com/Bertrandbenj -Dtoken=GH_TOKEN

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          directory: core/build/publications/mavenJava
          maven_goals_phases: publish
